version: v1
spring:
    datasource:
        url: jdbc:postgresql://db-orders:5433/orders
        username: postgres
        password: 123
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081